package jp.co.futurenavigator.ptk.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.futurenavigator.ptk.dao.model.TtChat;
import jp.co.futurenavigator.ptk.dao.model.TtChatCondition;
import jp.co.futurenavigator.ptk.dao.model.TtChatKey;

@Mapper
public interface TtChatMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	long countByExample(TtChatCondition example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	int deleteByExample(TtChatCondition example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	int deleteByPrimaryKey(TtChatKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	int insertReturnedId(TtChat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	int insert(TtChat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	int insertSelectiveReturnedId(TtChat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	int insertSelective(TtChat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	List<TtChat> selectByExampleWithRowbounds(TtChatCondition example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	List<TtChat> selectByExample(TtChatCondition example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	TtChat selectByPrimaryKey(TtChatKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	int updateByExampleSelective(@Param("record") TtChat record, @Param("example") TtChatCondition example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	int updateByExample(@Param("record") TtChat record, @Param("example") TtChatCondition example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	int updateByPrimaryKeySelective(TtChat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	int updateByPrimaryKey(TtChat record);
}