package jp.co.futurenavigator.atk.dao.model;

import java.io.Serializable;

public class TtChat extends TtChatKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_chat.CHAT_TEXT
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    private String chatText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_chat
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_chat.CHAT_TEXT
     *
     * @return the value of tt_chat.CHAT_TEXT
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    public String getChatText() {
        return chatText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_chat.CHAT_TEXT
     *
     * @param chatText the value for tt_chat.CHAT_TEXT
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    public void setChatText(String chatText) {
        this.chatText = chatText == null ? null : chatText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chat
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chatText=").append(chatText);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chat
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TtChat other = (TtChat) that;
        return (this.getChatId() == null ? other.getChatId() == null : this.getChatId().equals(other.getChatId()))
            && (this.getChatterId() == null ? other.getChatterId() == null : this.getChatterId().equals(other.getChatterId()))
            && (this.getChatText() == null ? other.getChatText() == null : this.getChatText().equals(other.getChatText()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chat
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChatId() == null) ? 0 : getChatId().hashCode());
        result = prime * result + ((getChatterId() == null) ? 0 : getChatterId().hashCode());
        result = prime * result + ((getChatText() == null) ? 0 : getChatText().hashCode());
        return result;
    }
}