package jp.co.futurenavigator.ptk.dao.model;

import java.io.Serializable;

public class TtChatter implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tt_chatter.CHATTER_ID
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	private Long chatterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tt_chatter.CHATTER_NAME
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	private String chatterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tt_chatter.CHATTER_ID
	 * @return  the value of tt_chatter.CHATTER_ID
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public Long getChatterId() {
		return chatterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tt_chatter.CHATTER_ID
	 * @param chatterId  the value for tt_chatter.CHATTER_ID
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public void setChatterId(Long chatterId) {
		this.chatterId = chatterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tt_chatter.CHATTER_NAME
	 * @return  the value of tt_chatter.CHATTER_NAME
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public String getChatterName() {
		return chatterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tt_chatter.CHATTER_NAME
	 * @param chatterName  the value for tt_chatter.CHATTER_NAME
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public void setChatterName(String chatterName) {
		this.chatterName = chatterName == null ? null : chatterName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", chatterId=").append(chatterId);
		sb.append(", chatterName=").append(chatterName);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TtChatter other = (TtChatter) that;
		return (this.getChatterId() == null ? other.getChatterId() == null
				: this.getChatterId().equals(other.getChatterId()))
				&& (this.getChatterName() == null ? other.getChatterName() == null
						: this.getChatterName().equals(other.getChatterName()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getChatterId() == null) ? 0 : getChatterId().hashCode());
		result = prime * result + ((getChatterName() == null) ? 0 : getChatterName().hashCode());
		return result;
	}
}