package jp.co.futurenavigator.ptk.dao.model;

import java.util.ArrayList;
import java.util.List;

public class TtChatterCondition {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public TtChatterCondition() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andChatterIdIsNull() {
			addCriterion("CHATTER_ID is null");
			return (Criteria) this;
		}

		public Criteria andChatterIdIsNotNull() {
			addCriterion("CHATTER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andChatterIdEqualTo(Long value) {
			addCriterion("CHATTER_ID =", value, "chatterId");
			return (Criteria) this;
		}

		public Criteria andChatterIdNotEqualTo(Long value) {
			addCriterion("CHATTER_ID <>", value, "chatterId");
			return (Criteria) this;
		}

		public Criteria andChatterIdGreaterThan(Long value) {
			addCriterion("CHATTER_ID >", value, "chatterId");
			return (Criteria) this;
		}

		public Criteria andChatterIdGreaterThanOrEqualTo(Long value) {
			addCriterion("CHATTER_ID >=", value, "chatterId");
			return (Criteria) this;
		}

		public Criteria andChatterIdLessThan(Long value) {
			addCriterion("CHATTER_ID <", value, "chatterId");
			return (Criteria) this;
		}

		public Criteria andChatterIdLessThanOrEqualTo(Long value) {
			addCriterion("CHATTER_ID <=", value, "chatterId");
			return (Criteria) this;
		}

		public Criteria andChatterIdIn(List<Long> values) {
			addCriterion("CHATTER_ID in", values, "chatterId");
			return (Criteria) this;
		}

		public Criteria andChatterIdNotIn(List<Long> values) {
			addCriterion("CHATTER_ID not in", values, "chatterId");
			return (Criteria) this;
		}

		public Criteria andChatterIdBetween(Long value1, Long value2) {
			addCriterion("CHATTER_ID between", value1, value2, "chatterId");
			return (Criteria) this;
		}

		public Criteria andChatterIdNotBetween(Long value1, Long value2) {
			addCriterion("CHATTER_ID not between", value1, value2, "chatterId");
			return (Criteria) this;
		}

		public Criteria andChatterNameIsNull() {
			addCriterion("CHATTER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andChatterNameIsNotNull() {
			addCriterion("CHATTER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andChatterNameEqualTo(String value) {
			addCriterion("CHATTER_NAME =", value, "chatterName");
			return (Criteria) this;
		}

		public Criteria andChatterNameNotEqualTo(String value) {
			addCriterion("CHATTER_NAME <>", value, "chatterName");
			return (Criteria) this;
		}

		public Criteria andChatterNameGreaterThan(String value) {
			addCriterion("CHATTER_NAME >", value, "chatterName");
			return (Criteria) this;
		}

		public Criteria andChatterNameGreaterThanOrEqualTo(String value) {
			addCriterion("CHATTER_NAME >=", value, "chatterName");
			return (Criteria) this;
		}

		public Criteria andChatterNameLessThan(String value) {
			addCriterion("CHATTER_NAME <", value, "chatterName");
			return (Criteria) this;
		}

		public Criteria andChatterNameLessThanOrEqualTo(String value) {
			addCriterion("CHATTER_NAME <=", value, "chatterName");
			return (Criteria) this;
		}

		public Criteria andChatterNameLike(String value) {
			addCriterion("CHATTER_NAME like", value, "chatterName");
			return (Criteria) this;
		}

		public Criteria andChatterNameNotLike(String value) {
			addCriterion("CHATTER_NAME not like", value, "chatterName");
			return (Criteria) this;
		}

		public Criteria andChatterNameIn(List<String> values) {
			addCriterion("CHATTER_NAME in", values, "chatterName");
			return (Criteria) this;
		}

		public Criteria andChatterNameNotIn(List<String> values) {
			addCriterion("CHATTER_NAME not in", values, "chatterName");
			return (Criteria) this;
		}

		public Criteria andChatterNameBetween(String value1, String value2) {
			addCriterion("CHATTER_NAME between", value1, value2, "chatterName");
			return (Criteria) this;
		}

		public Criteria andChatterNameNotBetween(String value1, String value2) {
			addCriterion("CHATTER_NAME not between", value1, value2, "chatterName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tt_chatter
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tt_chatter
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 01 23:31:23 JST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}