package jp.co.futurenavigator.ptk.dao.model;

import java.io.Serializable;

public class TtChatKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tt_chat.CHAT_ID
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	private Long chatId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tt_chat.CHATTER_ID
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	private Long chatterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tt_chat.CHAT_ID
	 * @return  the value of tt_chat.CHAT_ID
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public Long getChatId() {
		return chatId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tt_chat.CHAT_ID
	 * @param chatId  the value for tt_chat.CHAT_ID
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public void setChatId(Long chatId) {
		this.chatId = chatId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tt_chat.CHATTER_ID
	 * @return  the value of tt_chat.CHATTER_ID
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public Long getChatterId() {
		return chatterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tt_chat.CHATTER_ID
	 * @param chatterId  the value for tt_chat.CHATTER_ID
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	public void setChatterId(Long chatterId) {
		this.chatterId = chatterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", chatId=").append(chatId);
		sb.append(", chatterId=").append(chatterId);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TtChatKey other = (TtChatKey) that;
		return (this.getChatId() == null ? other.getChatId() == null : this.getChatId().equals(other.getChatId()))
				&& (this.getChatterId() == null ? other.getChatterId() == null
						: this.getChatterId().equals(other.getChatterId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tt_chat
	 * @mbg.generated  Thu Jul 04 23:37:02 JST 2019
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getChatId() == null) ? 0 : getChatId().hashCode());
		result = prime * result + ((getChatterId() == null) ? 0 : getChatterId().hashCode());
		return result;
	}
}