package jp.co.futurenavigator.atk.dao.mapper;

import java.util.List;
import jp.co.futurenavigator.atk.dao.model.TtChatter;
import jp.co.futurenavigator.atk.dao.model.TtChatterCondition;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TtChatterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    long countByExample(TtChatterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    int deleteByExample(TtChatterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    int deleteByPrimaryKey(Long chatterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    int insertReturnedId(TtChatter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    int insert(TtChatter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    int insertSelectiveReturnedId(TtChatter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    int insertSelective(TtChatter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    List<TtChatter> selectByExampleWithRowbounds(TtChatterCondition example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    List<TtChatter> selectByExample(TtChatterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    TtChatter selectByPrimaryKey(Long chatterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    int updateByExampleSelective(@Param("record") TtChatter record, @Param("example") TtChatterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    int updateByExample(@Param("record") TtChatter record, @Param("example") TtChatterCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    int updateByPrimaryKeySelective(TtChatter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_chatter
     *
     * @mbg.generated Mon Jul 01 23:31:23 JST 2019
     */
    int updateByPrimaryKey(TtChatter record);
}